language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"

deploy:
  provider: openshift
  user:
    - secure: "DR41KHnrBzPzdaoeOTxiElg+eiCnytQ3hnztZvqAieY4WK9ZSn8gfmJEIuieJEsoi7Iw6rr1ZBxA/pQxszfGayR1UyGl9qlCZ7w5zrzBfuToVUeDnxfe7OVDoEFT0GNv453yzGeZ8R6b9yBmymEk3TZ5BPUn1ZXXqaUclb0y3Yg="
  password:
    - secure: "JnV0E7jqoIOYvOY2DLG0dnPgz4n7ZsS8pCYalJ86M8AxK1L1oUhtDJtcPqXEw94Jzi/SOAfx8i/h1EXMoL4KlrPmAat6MVGa59+1v7VGspkbuQrbZTw8p7hvUyeYyDbXFEiPcPPv45XIwe09qqR9QTzs4lw0mkxyh5/PZTQfOno="
  app: browserquest
  domain: teambq

notifications:
  irc: "irc.synirc.net#browserquest"
