language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"

deploy:
    provider: openshift
    user: ADD-USERNAME-HERE
    password: ADD-PASSWORD-HERE
    app: browserquest
    domain: teambq
    key-name: bq
